// Master list of Indian cities for dropdowns and filters
// Matches backend src/config/cities.js

export const CITY_REGIONS: Record<string, string[]> = {
  'Delhi NCR': ['Delhi', 'Gurgaon', 'Noida', 'Faridabad', 'Ghaziabad', 'Greater Noida'],
  'Mumbai Metropolitan': ['Mumbai', 'Navi Mumbai', 'Thane', 'Kalyan'],
  'Bangalore': ['Bangalore'],
  'Hyderabad': ['Hyderabad', 'Secunderabad'],
  'Chennai': ['Chennai'],
  'Pune': ['Pune', 'Pimpri-Chinchwad'],
  'Kolkata': ['Kolkata', 'Howrah', 'Salt Lake'],
  'Ahmedabad': ['Ahmedabad', 'Gandhinagar'],
  'Jaipur': ['Jaipur'],
  'Lucknow': ['Lucknow'],
  'Chandigarh Tricity': ['Chandigarh', 'Mohali', 'Panchkula'],
  'Kochi': ['Kochi', 'Ernakulam'],
  'Goa': ['Panaji', 'Margao', 'Vasco da Gama'],
  'Indore': ['Indore'],
  'Jabalpur': ['Jabalpur'],
  'Bhopal': ['Bhopal'],
  'Coimbatore': ['Coimbatore'],
  'Vizag': ['Visakhapatnam'],
  'Nagpur': ['Nagpur'],
  'Patna': ['Patna'],
  'Bhubaneswar': ['Bhubaneswar'],
  'Dehradun': ['Dehradun', 'Rishikesh', 'Mussoorie'],
  'Mysore': ['Mysore'],
  'Mangalore': ['Mangalore'],
  'Trivandrum': ['Thiruvananthapuram'],
  'Vadodara': ['Vadodara'],
  'Surat': ['Surat'],
  'Kanpur': ['Kanpur'],
  'Varanasi': ['Varanasi'],
  'Amritsar': ['Amritsar'],
  'Udaipur': ['Udaipur'],
  'Jodhpur': ['Jodhpur'],
  'Ranchi': ['Ranchi'],
  'Guwahati': ['Guwahati'],
  'Shimla': ['Shimla', 'Manali'],
  'Pondicherry': ['Pondicherry'],
  'Srinagar': ['Srinagar'],
};

export const CITIES = Object.keys(CITY_REGIONS).sort();

// Predefined tags for plan creation and feed filtering
export const PLAN_TAGS = [
  'Hiking',
  'Trekking',
  'Coffee',
  'Brunch',
  'Dinner',
  'Drinks',
  'Rooftop',
  'House Party',
  'Beach',
  'Road Trip',
  'Movie',
  'Concert',
  'Stand-up',
  'Gaming',
  'Sports',
  'Cricket',
  'Football',
  'Badminton',
  'Gym',
  'Yoga',
  'Photography',
  'Art',
  'Music Jam',
  'Book Club',
  'Startup Meetup',
  'Tech Meetup',
  'Networking',
  'Workshop',
  'Potluck',
  'Picnic',
  'Camping',
  'Cycling',
  'Running',
  'Swimming',
  'Karaoke',
  'Board Games',
  'Volunteering',
  'Temple Run',
  'Sightseeing',
  'Festival',
  'Chill',
];
